[tool.poetry]
name = "skoltech-infrastructure"
version = "0.1.0"
description = ""
authors = ["Tema"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"
jupyter = "^1.0.0"
matplotlib = "^3.8.2"
pillow = "^10.1.0"
imageio = "^2.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
